language: python
python:
  - "3.6"

install:
  - pip install -r requirements-dev.txt

jobs:
  include:
    - stage: "Unit"
      name: "Unit Tests"
      script: pytest
    - stage: deploy
      name: "Deploy to AWS"
      script: echo "running serverless requires AWS credentials"
