service: todo-adminstration-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  region: ${opt:region, 'eu-west-1'}
  profile: ${opt:profile}


functions:
  user-list:
    handler: user-list.handler
    events:
      - http:
          path: user-list
          method: get
